TRELLO_KEY = ""
TRELLO_TOKEN = ""

NEW_CARDS_LIST_ID = ""

LABEL_ID_GREEN_DARK = ""
LABEL_ID_YELLOW_DARK = ""
LABEL_ID_ORANGE_DARK = ""
LABEL_ID_RED_DARK = ""
LABEL_ID_PURPLE_DARK = ""
LABEL_ID_BLUE_DARK = ""
LABEL_ID_SKY_DARK = ""
LABEL_ID_LIME_DARK = ""
LABEL_ID_PINK_DARK = ""
LABEL_ID_BLACK_DARK = ""

ZENDESK_EMAIL = ""
ZENDESK_TOKEN = ""
ZENDESK_SUBDOMAIN = ""

TRELLO_CARD_CUSTOM_FIELD = ""
